// <auto-generated />
using System;
using APIProductosWeb.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIProductosWeb.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240313162247_Inicio")]
    partial class Inicio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APIProductosWeb.Models.Categories_DB", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Watersports"
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "Soccer"
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryName = "Chess"
                        },
                        new
                        {
                            CategoryID = 4,
                            CategoryName = "Tenis"
                        });
                });

            modelBuilder.Entity("APIProductosWeb.Models.Products_DB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryID = 1,
                            Name = "Kayak",
                            Price = 286m
                        },
                        new
                        {
                            Id = 2,
                            CategoryID = 1,
                            Name = "Lifejacket",
                            Price = 48.95m
                        },
                        new
                        {
                            Id = 3,
                            CategoryID = 2,
                            Name = "Soccer Ball",
                            Price = 19.50m
                        },
                        new
                        {
                            Id = 4,
                            CategoryID = 2,
                            Name = "Corner Flags",
                            Price = 34.95m
                        },
                        new
                        {
                            Id = 5,
                            CategoryID = 3,
                            Name = "Stadium",
                            Price = 79500m
                        },
                        new
                        {
                            Id = 6,
                            CategoryID = 3,
                            Name = "Thinking Cap",
                            Price = 16.00m
                        },
                        new
                        {
                            Id = 7,
                            CategoryID = 3,
                            Name = "TUnsteady Chair",
                            Price = 29.95m
                        },
                        new
                        {
                            Id = 8,
                            CategoryID = 3,
                            Name = "Human Chess Board",
                            Price = 75m
                        },
                        new
                        {
                            Id = 9,
                            CategoryID = 3,
                            Name = "Bling Bling King",
                            Price = 1200m
                        });
                });

            modelBuilder.Entity("APIProductosWeb.Models.Products_DB", b =>
                {
                    b.HasOne("APIProductosWeb.Models.Categories_DB", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
